services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: xlsxworld-backend
    restart: unless-stopped
    environment:
      - CORS_ORIGINS=${CORS_ORIGINS}
    expose:
      - "8000"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    external: true
