export interface ToolItem {
  href: string;
  slug: string;
  icon: string;
  category: string;
  commingSoon?: boolean;
  isNew?: boolean;
}

export const toolItems: ToolItem[] = [
  {
    href: "/tools/inspect-sheets",
    slug: "inspect-sheets",
    icon: "👀",
    category: "Inspect",
  },
  {
    href: "/tools/merge-sheets",
    slug: "merge-sheets",
    icon: "🔗",
    category: "Merge",
  },
  {
    href: "/tools/append-workbooks",
    slug: "append-workbooks",
    icon: "🧩",
    category: "Merge",
  },
  {
    href: "/tools/split-sheet",
    slug: "split-sheet",
    icon: "✂️",
    category: "Split",
  },
  {
    href: "/tools/split-workbook",
    slug: "split-workbook",
    icon: "🍱",
    category: "Split",
  },
  {
    href: "/tools/xlsx-to-csv",
    slug: "xlsx-to-csv",
    icon: "🔁",
    category: "Convert",
  },
  {
    href: "/tools/csv-to-xlsx",
    slug: "csv-to-xlsx",
    icon: "📄",
    category: "Convert",
  },
  {
    href: "/tools/xlsx-to-pdf",
    slug: "xlsx-to-pdf",
    icon: "🖨️",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/pdf-to-xlsx",
    slug: "pdf-to-xlsx",
    icon: "📥",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/xlsx-to-json",
    slug: "xlsx-to-json",
    icon: "🧾",
    category: "Convert",
  },
  {
    href: "/tools/json-to-xlsx",
    slug: "json-to-xlsx",
    icon: "🗂️",
    category: "Convert",
  },
  {
    href: "/tools/xlsx-to-sql",
    slug: "xlsx-to-sql",
    icon: "💾",
    category: "Convert",
    isNew: true,
  },
  {
    href: "/tools/sql-to-xlsx",
    slug: "sql-to-xlsx",
    icon: "🛢️",
    category: "Convert",
    isNew: true,
  },
  {
    href: "/tools/xlsx-to-xml",
    slug: "xlsx-to-xml",
    icon: "🧬",
    category: "Convert",
    isNew: true,
  },
  {
    href: "/tools/xml-to-xlsx",
    slug: "xml-to-xlsx",
    icon: "📦",
    category: "Convert",
    isNew: true,
  },
  {
    href: "/tools/remove-empty-rows",
    slug: "remove-empty-rows",
    icon: "🚫",
    category: "Clean",
    commingSoon: true,
  },
  {
    href: "/tools/remove-duplicates",
    slug: "remove-duplicates",
    icon: "🧹",
    category: "Clean",
  },
  {
    href: "/tools/trim-spaces",
    slug: "trim-spaces",
    icon: "🧼",
    category: "Clean",
  },
  {
    href: "/tools/normalize-case",
    slug: "normalize-case",
    icon: "🔤",
    category: "Clean",
  },
  {
    href: "/tools/find-replace",
    slug: "find-replace",
    icon: "🪄",
    category: "Clean",
  },
  {
    href: "/tools/summary-stats",
    slug: "summary-stats",
    icon: "📊",
    category: "Analyze",
    commingSoon: true,
  },
  {
    href: "/tools/pivot-builder",
    slug: "pivot-builder",
    icon: "🧮",
    category: "Analyze",
    commingSoon: true,
  },
  {
    href: "/tools/correlation-matrix",
    slug: "correlation-matrix",
    icon: "🧠",
    category: "Analyze",
    commingSoon: true,
  },
  {
    href: "/tools/freeze-header",
    slug: "freeze-header",
    icon: "📌",
    category: "Format",
    commingSoon: true,
  },
  {
    href: "/tools/auto-size-columns",
    slug: "auto-size-columns",
    icon: "📏",
    category: "Format",
    commingSoon: true,
  },
  {
    href: "/tools/format-dates",
    slug: "format-dates",
    icon: "📅",
    category: "Format",
    commingSoon: true,
  },
  {
    href: "/tools/number-formatting",
    slug: "number-formatting",
    icon: "💲",
    category: "Format",
    commingSoon: true,
  },
  {
    href: "/tools/sort-rows",
    slug: "sort-rows",
    icon: "🔃",
    category: "Data",
    commingSoon: true,
  },
  {
    href: "/tools/transpose-sheet",
    slug: "transpose-sheet",
    icon: "🔄",
    category: "Data",
    commingSoon: true,
  },
  {
    href: "/tools/fill-series",
    slug: "fill-series",
    icon: "➕",
    category: "Data",
    commingSoon: true,
  },
  {
    href: "/tools/combine-columns",
    slug: "combine-columns",
    icon: "🧬",
    category: "Data",
    commingSoon: true,
  },
  {
    href: "/tools/split-column",
    slug: "split-column",
    icon: "🪓",
    category: "Data",
    commingSoon: true,
  },
  {
    href: "/tools/validate-emails",
    slug: "validate-emails",
    icon: "✉️",
    category: "Validate",
    commingSoon: true,
  },
  {
    href: "/tools/detect-blanks",
    slug: "detect-blanks",
    icon: "⚠️",
    category: "Validate",
    commingSoon: true,
  },
  {
    href: "/tools/data-type-check",
    slug: "data-type-check",
    icon: "🧪",
    category: "Validate",
    commingSoon: true,
  },
  {
    href: "/tools/password-protect",
    slug: "password-protect",
    icon: "🔒",
    category: "Security",
    commingSoon: true,
  },
  {
    href: "/tools/remove-password",
    slug: "remove-password",
    icon: "🔓",
    category: "Security",
    commingSoon: true,
  },
  {
    href: "/tools/redact-data",
    slug: "redact-data",
    icon: "🕶️",
    category: "Security",
    commingSoon: true,
  },
  {
    href: "/tools/schedule-export",
    slug: "schedule-export",
    icon: "⏰",
    category: "Automate",
    commingSoon: true,
  },
];
