import type { LucideIcon } from "lucide-react";
import {
  Eye,
  Link,
  Puzzle,
  Scissors,
  LayoutGrid,
  RefreshCw,
  FileText,
  Printer,
  BookOpen,
  FileJson,
  FolderOpen,
  Database,
  HardDrive,
  Dna,
  Package,
  Ban,
  Eraser,
  Sparkles,
  CaseSensitive,
  Replace,
  BarChart3,
  Search,
  Scale,
  Pin,
  Ruler,
  Calendar,
  ArrowUpDown,
  RotateCw,
  Axe,
  Mail,
  AlertTriangle,
  Lock,
  Unlock,
} from "lucide-react";

export interface ToolItem {
  href: string;
  slug: string;
  icon: LucideIcon;
  category: string;
  commingSoon?: boolean;
  isNew?: boolean;
  related?: string[];
}

export const toolItems: ToolItem[] = [
  {
    href: "/tools/inspect-sheets",
    slug: "inspect-sheets",
    icon: Eye,
    category: "Inspect",
    related: ["scan-formula-errors", "compare-workbooks", "detect-blanks"],
  },
  {
    href: "/tools/merge-sheets",
    slug: "merge-sheets",
    icon: Link,
    category: "Merge",
    related: ["append-workbooks", "split-sheet", "inspect-sheets"],
  },
  {
    href: "/tools/append-workbooks",
    slug: "append-workbooks",
    icon: Puzzle,
    category: "Merge",
    related: ["merge-sheets", "split-workbook", "inspect-sheets"],
  },
  {
    href: "/tools/split-sheet",
    slug: "split-sheet",
    icon: Scissors,
    category: "Split",
    related: ["split-workbook", "merge-sheets", "inspect-sheets"],
  },
  {
    href: "/tools/split-workbook",
    slug: "split-workbook",
    icon: LayoutGrid,
    category: "Split",
    related: ["split-sheet", "append-workbooks", "inspect-sheets"],
  },
  {
    href: "/tools/xlsx-to-csv",
    slug: "xlsx-to-csv",
    icon: RefreshCw,
    category: "Convert",
    related: ["csv-to-xlsx", "xlsx-to-json", "xlsx-to-pdf"],
  },
  {
    href: "/tools/csv-to-xlsx",
    slug: "csv-to-xlsx",
    icon: FileText,
    category: "Convert",
    related: ["xlsx-to-csv", "json-to-xlsx", "remove-duplicates"],
  },
  {
    href: "/tools/xlsx-to-pdf",
    slug: "xlsx-to-pdf",
    icon: Printer,
    category: "Convert",
    related: ["xlsx-to-csv", "freeze-header", "auto-size-columns"],
  },
  {
    href: "/tools/pdf-to-xlsx",
    slug: "pdf-to-xlsx",
    icon: BookOpen,
    category: "Convert",
    commingSoon: true,
    related: ["xlsx-to-pdf", "csv-to-xlsx"],
  },
  {
    href: "/tools/xlsx-to-json",
    slug: "xlsx-to-json",
    icon: FileJson,
    category: "Convert",
    related: ["json-to-xlsx", "xlsx-to-csv", "xlsx-to-xml"],
  },
  {
    href: "/tools/json-to-xlsx",
    slug: "json-to-xlsx",
    icon: FolderOpen,
    category: "Convert",
    related: ["xlsx-to-json", "csv-to-xlsx", "xml-to-xlsx"],
  },
  {
    href: "/tools/xlsx-to-sql",
    slug: "xlsx-to-sql",
    icon: Database,
    category: "Convert",
    related: ["sql-to-xlsx", "xlsx-to-csv", "xlsx-to-json"],
  },
  {
    href: "/tools/sql-to-xlsx",
    slug: "sql-to-xlsx",
    icon: HardDrive,
    category: "Convert",
    related: ["xlsx-to-sql", "csv-to-xlsx", "json-to-xlsx"],
  },
  {
    href: "/tools/xlsx-to-xml",
    slug: "xlsx-to-xml",
    icon: Dna,
    category: "Convert",
    related: ["xml-to-xlsx", "xlsx-to-json", "xlsx-to-csv"],
  },
  {
    href: "/tools/xml-to-xlsx",
    slug: "xml-to-xlsx",
    icon: Package,
    category: "Convert",
    related: ["xlsx-to-xml", "json-to-xlsx", "csv-to-xlsx"],
  },
  {
    href: "/tools/remove-empty-rows",
    slug: "remove-empty-rows",
    icon: Ban,
    category: "Clean",
    related: ["remove-duplicates", "detect-blanks", "trim-spaces"],
  },
  {
    href: "/tools/remove-duplicates",
    slug: "remove-duplicates",
    icon: Eraser,
    category: "Clean",
    related: ["trim-spaces", "normalize-case", "find-replace"],
  },
  {
    href: "/tools/trim-spaces",
    slug: "trim-spaces",
    icon: Sparkles,
    category: "Clean",
    related: ["normalize-case", "find-replace", "remove-duplicates"],
  },
  {
    href: "/tools/normalize-case",
    slug: "normalize-case",
    icon: CaseSensitive,
    category: "Clean",
    related: ["trim-spaces", "find-replace", "remove-duplicates"],
  },
  {
    href: "/tools/find-replace",
    slug: "find-replace",
    icon: Replace,
    category: "Clean",
    related: ["trim-spaces", "normalize-case", "remove-duplicates"],
  },
  {
    href: "/tools/summary-stats",
    slug: "summary-stats",
    icon: BarChart3,
    category: "Analyze",
    isNew: true,
    related: ["scan-formula-errors", "compare-workbooks", "inspect-sheets"],
  },
  {
    href: "/tools/scan-formula-errors",
    slug: "scan-formula-errors",
    icon: Search,
    category: "Analyze",
    isNew: true,
    related: ["inspect-sheets", "compare-workbooks", "summary-stats"],
  },
  {
    href: "/tools/compare-workbooks",
    slug: "compare-workbooks",
    icon: Scale,
    category: "Analyze",
    isNew: true,
    related: ["inspect-sheets", "scan-formula-errors", "summary-stats"],
  },
  {
    href: "/tools/freeze-header",
    slug: "freeze-header",
    icon: Pin,
    category: "Format",
    related: ["auto-size-columns", "sort-rows", "xlsx-to-pdf"],
  },
  {
    href: "/tools/auto-size-columns",
    slug: "auto-size-columns",
    icon: Ruler,
    category: "Format",
    related: ["freeze-header", "xlsx-to-pdf", "trim-spaces"],
  },
  {
    href: "/tools/format-dates",
    slug: "format-dates",
    icon: Calendar,
    category: "Format",
    commingSoon: true,
    related: ["normalize-case", "find-replace"],
  },
  {
    href: "/tools/sort-rows",
    slug: "sort-rows",
    icon: ArrowUpDown,
    category: "Data",
    related: ["remove-duplicates", "split-column", "transpose-sheet"],
  },
  {
    href: "/tools/transpose-sheet",
    slug: "transpose-sheet",
    icon: RotateCw,
    category: "Data",
    related: ["split-column", "sort-rows", "inspect-sheets"],
  },
  {
    href: "/tools/split-column",
    slug: "split-column",
    icon: Axe,
    category: "Data",
    related: ["find-replace", "sort-rows", "transpose-sheet"],
  },
  {
    href: "/tools/validate-emails",
    slug: "validate-emails",
    icon: Mail,
    category: "Validate",
    related: ["detect-blanks", "find-replace", "normalize-case"],
  },
  {
    href: "/tools/detect-blanks",
    slug: "detect-blanks",
    icon: AlertTriangle,
    category: "Validate",
    related: ["validate-emails", "remove-empty-rows", "inspect-sheets"],
  },
  {
    href: "/tools/password-protect",
    slug: "password-protect",
    icon: Lock,
    category: "Security",
    related: ["remove-password", "inspect-sheets"],
  },
  {
    href: "/tools/remove-password",
    slug: "remove-password",
    icon: Unlock,
    category: "Security",
    related: ["password-protect", "inspect-sheets"],
  },
];

// Popular tools shown when the "Popular" filter is active on the homepage.
// Order matters — these are the recommended entry points for new users.
export const FEATURED_TOOL_SLUGS = [
  "inspect-sheets",
  "xlsx-to-csv",
  "csv-to-xlsx",
  "remove-duplicates",
  "merge-sheets",
  "append-workbooks",
  "split-workbook",
  "xlsx-to-json",
  "xlsx-to-pdf",
  "trim-spaces",
  "find-replace",
  "scan-formula-errors",
  "sort-rows",
  "detect-blanks",
  "freeze-header",
];

// Hidden list for future consideration (not shown in the grid)
export const FUTURE_TOOLS = [
  { slug: "pivot-builder", category: "Analyze", note: "Create pivot-style aggregations" },
];
