# Use the official PostgreSQL image from Docker Hub
FROM postgres:lts-alpine

# Expose PostgreSQL port
EXPOSE 5432

# Optional: Add initialization scripts
# COPY ./init.sql /docker-entrypoint-initdb.d/