// No React import needed since we now avoid JSX and use plain strings for icons.
export interface ToolItem {
  href: string;
  title: string;
  heading: string;
  description: string;
  icon: string; // simple emoji string
  category: string;
  slug: string; // unique route segment
  commingSoon?: boolean;
  isNew?: boolean;
}

// Broad coverage of common XLSX-related actions
export const toolItems: ToolItem[] = [
  // Inspect & Explore
  {
    href: "/tools/inspect-sheets",
    slug: "inspect-sheets",
    title: "Inspect Sheets",
    heading: "Inspect Sheets",
    description: "Inspect sheet structure with filters, sorting, and quick stats before running other tools.",
    icon: "👀",
    category: "Inspect",
    isNew: true,
  },

  // Merge / Split
  {
    href: "/tools/merge-sheets",
    slug: "merge-sheets",
    title: "Merge Sheets",
    heading: "Merge Sheets",
    description: "Merge selected sheets from one workbook into a single sheet using one shared header row.",
    icon: "🔗",
    category: "Merge",
    commingSoon: false,
    isNew: true,
  },
  {
    href: "/tools/append-workbooks",
    slug: "append-workbooks",
    title: "Append Workbooks",
    heading: "Append Workbooks",
    description: "Append rows from multiple workbooks into one sheet, with file order controls and a custom output sheet name.",
    icon: "🧩",
    category: "Merge",
    commingSoon: false,
    isNew: true,
  },
  {
    href: "/tools/split-sheet",
    slug: "split-sheet",
    title: "Split Sheet",
    heading: "Split Sheet",
    description: "Split one sheet by row count and customize output names with your own base label and numbering style.",
    icon: "✂️",
    category: "Split",
    commingSoon: false,
    isNew: true,
  },
  {
    href: "/tools/split-workbook",
    slug: "split-workbook",
    title: "Split Workbook",
    heading: "Split Workbook",
    description: "Split a workbook into a ZIP containing one XLSX file per source sheet.",
    icon: "🍱",
    category: "Split",
    commingSoon: false,
    isNew: true,
  },

  // Convert
  {
    href: "/tools/xlsx-to-csv",
    slug: "xlsx-to-csv",
    title: "XLSX → CSV",
    heading: "XLSX → CSV",
    description: "Export one sheet as CSV or multiple selected sheets as a ZIP of CSV files.",
    icon: "🔁",
    category: "Convert",
    commingSoon: false,
    isNew: true,
  },
  {
    href: "/tools/csv-to-xlsx",
    slug: "csv-to-xlsx",
    title: "CSV → XLSX",
    heading: "CSV → XLSX",
    description: "Convert a CSV into a single-sheet XLSX with configurable delimiter and sheet name.",
    icon: "📄",
    category: "Convert",
    commingSoon: false,
    isNew: true,
  },
  {
    href: "/tools/xlsx-to-pdf",
    slug: "xlsx-to-pdf",
    title: "XLSX → PDF",
    heading: "XLSX → PDF",
    description: "Export selected sheets to printable PDF files.",
    icon: "🖨️",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/pdf-to-xlsx",
    slug: "pdf-to-xlsx",
    title: "PDF → XLSX",
    heading: "PDF → XLSX",
    description: "Extract tables from PDFs into editable XLSX sheets.",
    icon: "📥",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/xlsx-to-json",
    slug: "xlsx-to-json",
    title: "XLSX → JSON",
    heading: "XLSX → JSON",
    description: "Export sheet data to JSON for APIs and workflows.",
    icon: "🧾",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/json-to-xlsx",
    slug: "json-to-xlsx",
    title: "JSON → XLSX",
    heading: "JSON → XLSX",
    description: "Create XLSX workbooks from JSON arrays or objects.",
    icon: "🗂️",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/xlsx-to-sql",
    slug: "xlsx-to-sql",
    title: "XLSX → SQL",
    heading: "XLSX → SQL",
    description: "Generate SQL CREATE and INSERT statements.",
    icon: "💾",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/sql-to-xlsx",
    slug: "sql-to-xlsx",
    title: "SQL → XLSX",
    heading: "SQL → XLSX",
    description: "Run SQL queries and export result sets to XLSX.",
    icon: "🛢️",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/xlsx-to-xml",
    slug: "xlsx-to-xml",
    title: "XLSX → XML",
    heading: "XLSX → XML",
    description: "Transform sheet rows into XML documents.",
    icon: "🧬",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/xml-to-xlsx",
    slug: "xml-to-xlsx",
    title: "XML → XLSX",
    heading: "XML → XLSX",
    description: "Import XML feeds and map nodes to rows and columns.",
    icon: "📦",
    category: "Convert",
    commingSoon: true,
  },

  // Clean & Normalize
  {
    href: "/tools/remove-duplicates",
    slug: "remove-duplicates",
    title: "Remove Duplicates",
    heading: "Remove Duplicates",
    description: "Find and remove duplicate rows based on selected columns.",
    icon: "🧹",
    category: "Clean",
    commingSoon: true,
  },
  {
    href: "/tools/trim-spaces",
    slug: "trim-spaces",
    title: "Trim Spaces",
    heading: "Trim Spaces",
    description: "Trim leading and trailing whitespace from columns.",
    icon: "✂️",
    category: "Clean",
    commingSoon: true,
  },
  {
    href: "/tools/normalize-case",
    slug: "normalize-case",
    title: "Normalize Case",
    heading: "Normalize Case",
    description: "Normalize text to upper, lower, or title case.",
    icon: "🔤",
    category: "Clean",
    commingSoon: true,
  },
  {
    href: "/tools/find-replace",
    slug: "find-replace",
    title: "Find & Replace",
    heading: "Find & Replace",
    description: "Search and replace values or regex patterns across sheets or columns.",
    icon: "🪄",
    category: "Clean",
    commingSoon: true,
  },

  // Analyze
  {
    href: "/tools/summary-stats",
    slug: "summary-stats",
    title: "Summary Stats",
    heading: "Summary Stats",
    description: "Calculate summary statistics (count, mean, median, sum, stddev).",
    icon: "📊",
    category: "Analyze",
    commingSoon: true,
  },
  {
    href: "/tools/pivot-builder",
    slug: "pivot-builder",
    title: "Pivot Builder",
    heading: "Pivot Builder",
    description: "Create pivot-style aggregations and group-by summaries.",
    icon: "🧮",
    category: "Analyze",
    commingSoon: true,
  },
  {
    href: "/tools/correlation-matrix",
    slug: "correlation-matrix",
    title: "Correlation Matrix",
    heading: "Correlation Matrix",
    description: "Compute correlations between numeric columns.",
    icon: "🧠",
    category: "Analyze",
    commingSoon: true,
  },

  // Format / Layout
  {
    href: "/tools/auto-size-columns",
    slug: "auto-size-columns",
    title: "Auto Size Columns",
    heading: "Auto Size Columns",
    description: "Auto-fit column widths to their content.",
    icon: "📏",
    category: "Format",
    commingSoon: true,
  },
  {
    href: "/tools/format-dates",
    slug: "format-dates",
    title: "Format Dates",
    heading: "Format Dates",
    description: "Detect and normalize date/time formats across columns.",
    icon: "📅",
    category: "Format",
    commingSoon: true,
  },
  {
    href: "/tools/number-formatting",
    slug: "number-formatting",
    title: "Number Formatting",
    heading: "Number Formatting",
    description: "Apply number formats like currency, percentage, and decimals.",
    icon: "💲",
    category: "Format",
    commingSoon: true,
  },

  // Data Manipulation
  {
    href: "/tools/transpose-sheet",
    slug: "transpose-sheet",
    title: "Transpose Sheet",
    heading: "Transpose Sheet",
    description: "Transpose a sheet to swap rows and columns.",
    icon: "🔄",
    category: "Data",
    commingSoon: true,
  },
  {
    href: "/tools/fill-series",
    slug: "fill-series",
    title: "Fill Series",
    heading: "Fill Series",
    description: "Fill a column with sequential values or patterns.",
    icon: "➕",
    category: "Data",
    commingSoon: true,
  },
  {
    href: "/tools/combine-columns",
    slug: "combine-columns",
    title: "Combine Columns",
    heading: "Combine Columns",
    description: "Combine columns into a single field using a separator.",
    icon: "🧬",
    category: "Data",
    commingSoon: true,
  },
  {
    href: "/tools/split-column",
    slug: "split-column",
    title: "Split Column",
    heading: "Split Column",
    description: "Split a column into multiple columns by delimiter or pattern.",
    icon: "🪓",
    category: "Data",
    commingSoon: true,
  },

  // Validation
  {
    href: "/tools/validate-emails",
    slug: "validate-emails",
    title: "Validate Emails",
    heading: "Validate Emails",
    description: "Identify entries that do not match common email patterns.",
    icon: "✉️",
    category: "Validate",
    commingSoon: true,
  },
  {
    href: "/tools/detect-blanks",
    slug: "detect-blanks",
    title: "Detect Blanks",
    heading: "Detect Blanks",
    description: "Locate missing or empty required fields.",
    icon: "⚠️",
    category: "Validate",
    commingSoon: true,
  },
  {
    href: "/tools/data-type-check",
    slug: "data-type-check",
    title: "Data Type Check",
    heading: "Data Type Check",
    description: "Detect inconsistent data types within columns.",
    icon: "🧪",
    category: "Validate",
    commingSoon: true,
  },

  // Security
  {
    href: "/tools/password-protect",
    slug: "password-protect",
    title: "Password Protect",
    heading: "Password Protect",
    description: "Apply password protection to restrict opening or editing.",
    icon: "🔒",
    category: "Security",
    commingSoon: true,
  },
  {
    href: "/tools/remove-password",
    slug: "remove-password",
    title: "Remove Password",
    heading: "Remove Password",
    description: "Remove password protection given correct credentials.",
    icon: "🔓",
    category: "Security",
    commingSoon: true,
  },
  {
    href: "/tools/redact-data",
    slug: "redact-data",
    title: "Redact Data",
    heading: "Redact Data",
    description: "Mask sensitive columns to protect confidential data.",
    icon: "🕶️",
    category: "Security",
    commingSoon: true,
  },

  // Import / Export
  {
    href: "/tools/import-google-sheets",
    slug: "import-google-sheets",
    title: "Import Google Sheets",
    heading: "Import Google Sheets",
    description: "Import data from a Google Sheets document or range.",
    icon: "☁️",
    category: "Import/Export",
    commingSoon: true,
  },
  {
    href: "/tools/export-google-sheets",
    slug: "export-google-sheets",
    title: "Export Google Sheets",
    heading: "Export Google Sheets",
    description: "Export workbook data to a connected Google Sheets document.",
    icon: "🚀",
    category: "Import/Export",
    commingSoon: true,
  },
  {
    href: "/tools/import-xml-feed",
    slug: "import-xml-feed",
    title: "Import XML Feed",
    heading: "Import XML Feed",
    description: "Import structured XML data from a file or feed.",
    icon: "🛰️",
    category: "Import/Export",
    commingSoon: true,
  },

  // Automation
  {
    href: "/tools/schedule-export",
    slug: "schedule-export",
    title: "Schedule Export",
    heading: "Schedule Export",
    description: "Schedule recurring exports (CSV/XLSX) for automatic delivery.",
    icon: "⏰",
    category: "Automate",
    commingSoon: true,
  },
  {
    href: "/tools/macro-runner",
    slug: "macro-runner",
    title: "Macro Runner",
    heading: "Macro Runner",
    description: "Run VBA macros contained in workbooks (use with caution).",
    icon: "🤖",
    category: "Automate",
    commingSoon: true,
  },
];
