// No React import needed since we now avoid JSX and use plain strings for icons.
export interface ToolItem {
  href: string;
  title: string;
  heading: string;
  description: string;
  icon: string; // simple emoji string
  category: string;
  slug: string; // unique route segment
  commingSoon?: boolean;
}

// Broad coverage of common XLSX-related actions
export const toolItems: ToolItem[] = [
  // Inspect & Explore
  {
    href: "/tools/inspect-sheets",
    slug: "inspect-sheets",
    title: "Inspect Sheets",
    heading: "Inspect Sheets",
    description:
      "Instantly preview every sheet, headers, and sample rows without opening Excel.",
    icon: "👀",
    category: "Inspect",
  },

  // Merge / Split
  {
    href: "/tools/merge-sheets",
    slug: "merge-sheets",
    title: "Merge Sheets",
    heading: "Merge Sheets",
    description: "Combine multiple sheets into one.",
    icon: "🔗",
    category: "Merge",
    commingSoon: true,
  },
  {
    href: "/tools/append-workbooks",
    slug: "append-workbooks",
    title: "Append Workbooks",
    heading: "Append Workbooks",
    description: "Stack workbooks vertically into one sheet.",
    icon: "🧩",
    category: "Merge",
    commingSoon: true,
  },
  {
    href: "/tools/split-sheet",
    slug: "split-sheet",
    title: "Split Sheet",
    heading: "Split Sheet",
    description: "Split a sheet by size or column value.",
    icon: "✂️",
    category: "Split",
    commingSoon: true,
  },
  {
    href: "/tools/split-workbook",
    slug: "split-workbook",
    title: "Split Workbook",
    heading: "Split Workbook",
    description: "Export each sheet into a separate file.",
    icon: "🍱",
    category: "Split",
    commingSoon: true,
  },

  // Convert
  {
    href: "/tools/xlsx-to-csv",
    slug: "xlsx-to-csv",
    title: "XLSX → CSV",
    heading: "XLSX → CSV",
    description: "Convert XLSX to CSV format.",
    icon: "🔁",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/csv-to-xlsx",
    slug: "csv-to-xlsx",
    title: "CSV → XLSX",
    heading: "CSV → XLSX",
    description: "Turn CSV files into structured XLSX.",
    icon: "📄",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/xlsx-to-pdf",
    slug: "xlsx-to-pdf",
    title: "XLSX → PDF",
    heading: "XLSX → PDF",
    description: "Export polished printable PDFs.",
    icon: "🖨️",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/pdf-to-xlsx",
    slug: "pdf-to-xlsx",
    title: "PDF → XLSX",
    heading: "PDF → XLSX",
    description: "Extract tables from PDF into sheets.",
    icon: "📥",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/xlsx-to-json",
    slug: "xlsx-to-json",
    title: "XLSX → JSON",
    heading: "XLSX → JSON",
    description: "Serialize data to JSON.",
    icon: "🧾",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/json-to-xlsx",
    slug: "json-to-xlsx",
    title: "JSON → XLSX",
    heading: "JSON → XLSX",
    description: "Build sheets from JSON arrays.",
    icon: "🗂️",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/xlsx-to-sql",
    slug: "xlsx-to-sql",
    title: "XLSX → SQL",
    heading: "XLSX → SQL",
    description: "Generate CREATE & INSERT statements.",
    icon: "💾",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/sql-to-xlsx",
    slug: "sql-to-xlsx",
    title: "SQL → XLSX",
    heading: "SQL → XLSX",
    description: "Run queries & export result sets.",
    icon: "🛢️",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/xlsx-to-xml",
    slug: "xlsx-to-xml",
    title: "XLSX → XML",
    heading: "XLSX → XML",
    description: "Transform sheet data into XML.",
    icon: "🧬",
    category: "Convert",
    commingSoon: true,
  },
  {
    href: "/tools/xml-to-xlsx",
    slug: "xml-to-xlsx",
    title: "XML → XLSX",
    heading: "XML → XLSX",
    description: "Import XML nodes as rows.",
    icon: "📦",
    category: "Convert",
    commingSoon: true,
  },

  // Clean & Normalize
  {
    href: "/tools/remove-duplicates",
    slug: "remove-duplicates",
    title: "Remove Duplicates",
    heading: "Remove Duplicates",
    description: "Eliminate duplicate rows.",
    icon: "🧹",
    category: "Clean",
    commingSoon: true,
  },
  {
    href: "/tools/trim-spaces",
    slug: "trim-spaces",
    title: "Trim Spaces",
    heading: "Trim Spaces",
    description: "Remove leading & trailing whitespace.",
    icon: "✂️",
    category: "Clean",
    commingSoon: true,
  },
  {
    href: "/tools/normalize-case",
    slug: "normalize-case",
    title: "Normalize Case",
    heading: "Normalize Case",
    description: "Upper / lower / title case fields.",
    icon: "🔤",
    category: "Clean",
    commingSoon: true,
  },
  {
    href: "/tools/find-replace",
    slug: "find-replace",
    title: "Find & Replace",
    heading: "Find & Replace",
    description: "Bulk replace patterns.",
    icon: "🪄",
    category: "Clean",
    commingSoon: true,
  },

  // Analyze
  {
    href: "/tools/summary-stats",
    slug: "summary-stats",
    title: "Summary Stats",
    heading: "Summary Stats",
    description: "Auto-calc count, mean, median, etc.",
    icon: "📊",
    category: "Analyze",
    commingSoon: true,
  },
  {
    href: "/tools/pivot-builder",
    slug: "pivot-builder",
    title: "Pivot Builder",
    heading: "Pivot Builder",
    description: "Create pivot-style aggregations.",
    icon: "🧮",
    category: "Analyze",
    commingSoon: true,
  },
  {
    href: "/tools/correlation-matrix",
    slug: "correlation-matrix",
    title: "Correlation Matrix",
    heading: "Correlation Matrix",
    description: "Measure relationships between columns.",
    icon: "🧠",
    category: "Analyze",
    commingSoon: true,
  },

  // Format / Layout
  {
    href: "/tools/auto-size-columns",
    slug: "auto-size-columns",
    title: "Auto Size Columns",
    heading: "Auto Size Columns",
    description: "Best-fit column widths.",
    icon: "📏",
    category: "Format",
    commingSoon: true,
  },
  {
    href: "/tools/format-dates",
    slug: "format-dates",
    title: "Format Dates",
    heading: "Format Dates",
    description: "Unify date/time formats.",
    icon: "📅",
    category: "Format",
    commingSoon: true,
  },
  {
    href: "/tools/number-formatting",
    slug: "number-formatting",
    title: "Number Formatting",
    heading: "Number Formatting",
    description: "Apply currency & decimal styles.",
    icon: "💲",
    category: "Format",
    commingSoon: true,
  },

  // Data Manipulation
  {
    href: "/tools/transpose-sheet",
    slug: "transpose-sheet",
    title: "Transpose Sheet",
    heading: "Transpose Sheet",
    description: "Swap rows and columns.",
    icon: "🔄",
    category: "Data",
    commingSoon: true,
  },
  {
    href: "/tools/fill-series",
    slug: "fill-series",
    title: "Fill Series",
    heading: "Fill Series",
    description: "Generate sequential values.",
    icon: "➕",
    category: "Data",
    commingSoon: true,
  },
  {
    href: "/tools/combine-columns",
    slug: "combine-columns",
    title: "Combine Columns",
    heading: "Combine Columns",
    description: "Concatenate fields into one.",
    icon: "🧬",
    category: "Data",
    commingSoon: true,
  },
  {
    href: "/tools/split-column",
    slug: "split-column",
    title: "Split Column",
    heading: "Split Column",
    description: "Split a column by delimiter.",
    icon: "🪓",
    category: "Data",
    commingSoon: true,
  },

  // Validation
  {
    href: "/tools/validate-emails",
    slug: "validate-emails",
    title: "Validate Emails",
    heading: "Validate Emails",
    description: "Flag invalid email formats.",
    icon: "✉️",
    category: "Validate",
    commingSoon: true,
  },
  {
    href: "/tools/detect-blanks",
    slug: "detect-blanks",
    title: "Detect Blanks",
    heading: "Detect Blanks",
    description: "Locate empty required fields.",
    icon: "⚠️",
    category: "Validate",
    commingSoon: true,
  },
  {
    href: "/tools/data-type-check",
    slug: "data-type-check",
    title: "Data Type Check",
    heading: "Data Type Check",
    description: "Identify inconsistent types.",
    icon: "🧪",
    category: "Validate",
    commingSoon: true,
  },

  // Security
  {
    href: "/tools/password-protect",
    slug: "password-protect",
    title: "Password Protect",
    heading: "Password Protect",
    description: "Encrypt workbook with a password.",
    icon: "🔒",
    category: "Security",
    commingSoon: true,
  },
  {
    href: "/tools/remove-password",
    slug: "remove-password",
    title: "Remove Password",
    heading: "Remove Password",
    description: "Unlock protected workbooks.",
    icon: "🔓",
    category: "Security",
    commingSoon: true,
  },
  {
    href: "/tools/redact-data",
    slug: "redact-data",
    title: "Redact Data",
    heading: "Redact Data",
    description: "Mask sensitive columns.",
    icon: "🕶️",
    category: "Security",
    commingSoon: true,
  },

  // Import / Export
  {
    href: "/tools/import-google-sheets",
    slug: "import-google-sheets",
    title: "Import Google Sheets",
    heading: "Import Google Sheets",
    description: "Pull data from Google Sheets.",
    icon: "☁️",
    category: "Import/Export",
    commingSoon: true,
  },
  {
    href: "/tools/export-google-sheets",
    slug: "export-google-sheets",
    title: "Export Google Sheets",
    heading: "Export Google Sheets",
    description: "Push updates to Google Sheets.",
    icon: "🚀",
    category: "Import/Export",
    commingSoon: true,
  },
  {
    href: "/tools/import-xml-feed",
    slug: "import-xml-feed",
    title: "Import XML Feed",
    heading: "Import XML Feed",
    description: "Load structured XML data.",
    icon: "🛰️",
    category: "Import/Export",
    commingSoon: true,
  },

  // Automation
  {
    href: "/tools/schedule-export",
    slug: "schedule-export",
    title: "Schedule Export",
    heading: "Schedule Export",
    description: "Automate periodic exports.",
    icon: "⏰",
    category: "Automate",
    commingSoon: true,
  },
  {
    href: "/tools/macro-runner",
    slug: "macro-runner",
    title: "Macro Runner",
    heading: "Macro Runner",
    description: "Execute workbook macros (VBA).",
    icon: "🤖",
    category: "Automate",
    commingSoon: true,
  },
];
